server:
  port: 0
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations:
            - classpath:config/telemetry/{application}
            - classpath:config/commerce/{application}
            - classpath:config/infra/{application}
eureka:
  instance:
    preferIpAddress: true
    instance-id: "${spring.cloud.client.ip-address}:${server.port}"
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
logging:
  level:
    web: trace
