spring:
  application:
    name: warehouse
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000
      discovery:
        enabled: true
        serviceId: config-server

eureka:
  instance:
    preferIpAddress: true
    instance-id: "${spring.cloud.client.ip-address}:${server.port}"
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/